apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  namespace: external-secrets
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: hazemhashem100/nodejs-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: RDS_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: secrets-manager-secret
              key: RDS_HOSTNAME
        - name: RDS_USERNAME
          valueFrom:
            secretKeyRef:
              name: secrets-manager-secret
              key: RDS_USERNAME
        - name: RDS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets-manager-secret
              key: RDS_PASSWORD
        - name: RDS_PORT
          valueFrom:
            secretKeyRef:
              name: secrets-manager-secret
              key: RDS_PORT

        - name: REDIS_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: secrets-manager-secret
              key: REDIS_HOSTNAME
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: secrets-manager-secret
              key: REDIS_PORT


---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: external-secrets

  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"

spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
